stages:
  - build-and-test
  - check-policies
  - build-docs

.build-and-test-template: &build-and-test-template
  #image: ubuntu-20.04
  stage: build-and-test
  timeout: 1h
  variables:
  script:
    - echo Success!

.check-formatting-template: &check-formatting-template
  image: python:3.9.19-bullseye
  stage: check-policies
  variables:
    FPRETTIFY_COMMAND: fprettify --config .fprettify.ini --diff --recursive src
  before_script:
    - pip install fprettify
  script:
    - cd "$CI_PROJECT_DIR"
    - "$FPRETTIFY_COMMAND"
    - if [[ ! -z "($FPRETTIFY_COMMAND)" ]]; then echo "::warning::Code formatting issues detected. See log for details."; exit 1; fi
  allow_failure: false
  timeout: 15m

.build-docs-template: &build-docs-template
  #image: ubuntu-latest
  stage: build-docs
  variables:
  script:
    - echo Success!

build-and-test:
  <<: *build-and-test-template
  needs: []
    
check-formatting:
  <<: *check-formatting-template
  needs: []
    
build-docs:
  <<: *build-docs-template
  needs: []
