name: Trigger GitLab CI

on: [pull_request] 

jobs:
  trigger-gitlab-ci:
    name: Test against https://gitlab.nektar.info/CFD-Xing/x3d2-ci
    runs-on: ubuntu-latest
    steps:
    - uses: xcompact3d/x3d2@v1
      with:
        url: https://gitlab.nektar.info
        project_id: 364
        token: ${{ secrets.GITLABCI }}
